source:https://www.youtube.com/watch?v=nJYFh4Dl-as

In [36]:
def shiftGrid(grid, k):
    result = []
    row = len(grid)
    col = len(grid[0])
    def posTval(r,c):
        posval = r*col+c
        return posval
    def valTpos(val):
        R = val//col
        C = val%col
        return R,C

    # result = []
    # for i in range(row):
    #     result.append([0]*col)
    result = [[0]*col for i in range(row)]
    
    for r in range(row):
        for c in range(col):
            newval = (posTval(r,c) + k) % (row*col) 
            newR, newC = valTpos(newval)
            result[newR][newC] = grid[r][c]

    print(result)
    return result

# grid = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
# k = 1
grid = [[1],[2],[3],[4],[7],[6],[5]]
k = 23
result = shiftGrid(grid,k)

[[6], [5], [1], [2], [3], [4], [7]]


In [17]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
array = [1,2,3,4,5,6,7,8,9,10,11,12]
print(len(a))
print(len(a[0]))
print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
4
3
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [38]:
result = []
row = 4
col = 3
for i in range(row):
    result.append([0]*col)
print(result)

result = [[0]*col for i in range(row)]
print(result)

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [39]:
grid = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(len(grid))
print(len(grid[0]))
print(grid[2][2])

4
3
9


In [13]:
grid = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(grid[2,2])

9
