## ML - ML

In [12]:
import numpy as np
def linear_regression_normal_equation(X,y):
    # Step 1: Convert X and y to NumPy arrays
    X = np.array(X)  # Convert feature matrix X to a NumPy array
    y = np.array(y).reshape(-1, 1)  # Convert target vector y to a column vector
    
    # Step 2: Compute the transpose of X
    X_transpose = X.T  # Transpose of X
    
    # Step 3: Compute X^T X (X_transpose dot X)
    X_transpose_X = X_transpose.dot(X)
    
    # Step 4: Compute the inverse of X^T X
    X_transpose_X_inv = np.linalg.inv(X_transpose_X)
    
    # Step 5: Compute X^T y (X_transpose dot y)
    X_transpose_y = X_transpose.dot(y)
    
    # Step 6: Compute theta using the normal equation
    theta = X_transpose_X_inv.dot(X_transpose_y)
    
    # Step 7: Round theta to 4 decimal places and flatten to a list
    theta_rounded = np.round(theta, 4)  # Round to 4 decimal places
    theta_flattened = theta_rounded.flatten().tolist()  # Flatten and convert to list
    
    # Step 8: Return the final coefficients
    return theta_flattened

# Test Case 1: Simple linear relationship
X1 = [[1, 1], [1, 2], [1, 3]]  # Feature matrix
y1 = [1, 2, 3]                 # Target vector
coefficients1 = linear_regression_normal_equation(X1, y1)
print("Coefficients (Test Case 1):", coefficients1)  # Expected: [0.0, 1.0]

# Test Case 2: Multiple features
X2 = [[1, 3, 4], [1, 2, 5], [1, 3, 2]]  # Feature matrix
y2 = [1, 2, 1]                          # Target vector
coefficients2 = linear_regression_normal_equation(X2, y2)
print("Coefficients (Test Case 2):", coefficients2)  # Expected: [4.0, -1.0, 0.0]

# Additional Test Case 3: Perfect linear relationship
X3 = [[1], [2], [3], [4]]
y3 = [2, 4, 6, 8]
coefficients3 = linear_regression_normal_equation(X3, y3)
print("Coefficients (Test Case 3):", coefficients3)  # Expected: [0.0, 2.0]

Coefficients (Test Case 1): [-0.0, 1.0]
Coefficients (Test Case 2): [4.0, -1.0, -0.0]
Coefficients (Test Case 3): [2.0]


## Understanding `np.linalg.inv`

The function `np.linalg.inv` in NumPy computes the **inverse of a square matrix**. The inverse of a matrix $A$ is another matrix $A^{-1}$ such that:

$$
A \cdot A^{-1} = A^{-1} \cdot A = I
$$

where $I$ is the **identity matrix** (a matrix with 1s on the diagonal and 0s elsewhere).

---

## Key Points

1. **Inverse of a Matrix**:
   - The inverse of a matrix $A$ is a matrix $A^{-1}$ that, when multiplied by $A$, gives the identity matrix $I$.
   - Not all matrices have an inverse. A matrix must be **square** (same number of rows and columns) and **non-singular** (its determinant is not zero) to have an inverse.

2. **Syntax**:
   ```python
   np.linalg.inv(A)

In [18]:
import numpy as np

# Define a 3x3 matrix
A = np.array([[2, 1, 3],
              [1, 2, 1],
              [3, 1, 2]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)

print("\nInverse of A:")
print(A_inv)

# Verify: A @ A_inv should give the identity matrix
identity = np.dot(A, A_inv)

print("\nA * A_inv (should be close to identity matrix):")
print(identity)

det_A = np.linalg.det(A)
print("Determinant of A:", det_A)


Matrix A:
[[2 1 3]
 [1 2 1]
 [3 1 2]]

Inverse of A:
[[-0.375 -0.125  0.625]
 [-0.125  0.625 -0.125]
 [ 0.625 -0.125 -0.375]]

A * A_inv (should be close to identity matrix):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinant of A: -8.000000000000002
