## ML - Linear Algebra 


## Transformation Matrix from Basis B to Basis C

### Introduction
In linear algebra, a transformation matrix is used to convert coordinates of vectors from one basis to another. Specifically, if we have two bases $ B $ and $ C $ in $ \mathbb{R}^n $, the transformation matrix $ P $ from $ B $ to $ C $ allows us to express vectors in terms of $ C $ instead of $ B $.

#### Key Formula
The transformation matrix $ P $ from $ B $ to $ C $ is given by:

$$
P = C^{-1} \cdot B
$$

- $ C $: The matrix whose columns are the basis vectors of $ C $.
- $ B $: The matrix whose columns are the basis vectors of $ B $.
- $ C^{-1} $: The inverse of the matrix $ C $.

### Steps to Compute $ P $

1. **Construct the Matrices $ B $ and $ C $**:
   - Each column of $ B $ represents a vector in basis $ B $.
   - Each column of $ C $ represents a vector in basis $ C $.

2. **Compute the Inverse of $ C $**:
   - Ensure $ C $ is invertible ($ \det(C) \neq 0 $).
   - Use numerical methods or formulas to compute $ C^{-1} $.

3. **Multiply $ C^{-1} $ by $ B $**:
   - Perform matrix multiplication to obtain $ P $.

4. **Interpret $ P $**:
   - Each column of $ P $ gives the coordinates of the corresponding basis vector of $ B $ expressed in terms of $ C $.

---

### Example Calculation

Let:

$$
B = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}, \quad
C = \begin{bmatrix} 1 & 2.3 & 3 \\ 4.4 & 25 & 6 \\ 7.4 & 8 & 9 \end{bmatrix}
$$

#### Step 1: Compute $ C^{-1} $
Using numerical methods, the inverse of $ C $ is:

$$
C^{-1} = \begin{bmatrix} -0.6772 & -0.0126 & 0.2342 \\ -0.0184 & 0.0505 & -0.0275 \\ 0.5732 & -0.0345 & -0.0569 \end{bmatrix}
$$

#### Step 2: Compute $ P $
Since $ B $ is the identity matrix, $ P = C^{-1} \cdot B $ simplifies to:

$$
P = C^{-1}
$$

Thus:

$$
P = \begin{bmatrix} -0.6772 & -0.0126 & 0.2342 \\ -0.0184 & 0.0505 & -0.0275 \\ 0.5732 & -0.0345 & -0.0569 \end{bmatrix}
$$

---



In [3]:
import numpy as np

def transformation_matrix(B, C):
    """
    Compute the transformation matrix P from basis B to C.

    Args:
        B: Basis matrix B (3x3, usually the identity matrix for R^3)
        C: Basis matrix C (3x3)

    Returns:
        Transformation matrix P (3x3)
    """
    # Convert B and C to numpy arrays
    B = np.array(B, dtype=float)
    C = np.array(C, dtype=float)

    # Compute the inverse of C
    C_inv = np.linalg.inv(C)

    # Compute the transformation matrix P
    P = np.dot(C_inv, B)

    return P

# Example input
B = [[1, 0, 0], 
     [0, 1, 0], 
     [0, 0, 1]]

C = [[1, 2.3, 3], 
     [4.4, 25, 6], 
     [7.4, 8, 9]]

# Compute transformation matrix
P = transformation_matrix(B, C)

# Print result with 4 decimal places
print(np.round(P, 4))


[[-0.6772 -0.0126  0.2342]
 [-0.0184  0.0505 -0.0275]
 [ 0.5732 -0.0345 -0.0569]]


## computing the adjugate matrix and verifying the inverse

### What is the Adjugate Matrix?

The **adjugate matrix** (denoted as $ \text{adj}(C) $) is a key component in computing the inverse of a square matrix. It is formed by rearranging the elements of the matrix and applying specific sign changes.

#### Formula for the Adjugate Matrix (2x2 Case)
For a $ 2 \times 2 $ matrix:

$$
C = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$

The adjugate matrix is:

$$
\text{adj}(C) = \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

---

### Computing the Inverse Using the Adjugate Matrix

The inverse of $ C $ (denoted as $ C^{-1} $) is computed using the formula:

$$
C^{-1} = \frac{1}{\det(C)} \cdot \text{adj}(C)
$$

Where:
- $ \det(C) = ad - bc $, the determinant of $ C $.
- $ \text{adj}(C) $ is the adjugate matrix.

#### Conditions for Inversibility:
- A matrix is invertible if and only if $ \det(C) \neq 0 $.

---

### Step-by-Step Example

Let:

$$
C = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

#### Step 1: Compute $ \det(C) $
The determinant is:

$$
\det(C) = (1 \cdot 4) - (3 \cdot 2) = 4 - 6 = -2
$$

Since $ \det(C) \neq 0 $, the matrix is invertible.

---

#### Step 2: Compute the Adjugate Matrix
Using the formula:

$$
\text{adj}(C) = \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

Substitute the elements of $ C $:

$$
\text{adj}(C) = \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix}
$$

---

#### Step 3: Compute $ C^{-1} $
Using the formula for the inverse:

$$
C^{-1} = \frac{1}{\det(C)} \cdot \text{adj}(C)
$$

Substitute $ \det(C) = -2 $ and $ \text{adj}(C) $:

$$
C^{-1} = \frac{1}{-2} \cdot \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix}
= \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}
$$

---

### Verification of the Inverse

To verify, multiply $ C $ by $ C^{-1} $ and ensure it equals the identity matrix:

$$
C \cdot C^{-1} = I
$$

For:

$$
C = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad C^{-1} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}
$$

The product is:

$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \cdot \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix} =
\begin{bmatrix} (1 \cdot -2 + 2 \cdot 1.5) & (1 \cdot 1 + 2 \cdot -0.5) \\ (3 \cdot -2 + 4 \cdot 1.5) & (3 \cdot 1 + 4 \cdot -0.5) \end{bmatrix}
$$

$$
= \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
$$

This is the identity matrix, confirming that the inverse is correct.

---

In [6]:
import numpy as np

def compute_adjugate(matrix):
    """
    Compute the adjugate of a 2x2 matrix.
    Args:
        matrix: 2x2 matrix as a list of lists.
    Returns:
        Adjugate matrix as a numpy array.
    """
    a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]
    # Adjugate matrix: swap diagonal elements, change signs of off-diagonals
    adj = np.array([[d, -b],
                    [-c, a]])
    return adj

def compute_inverse(matrix):
    """
    Compute the inverse of a 2x2 matrix using its determinant and adjugate.
    Args:
        matrix: 2x2 matrix as a list of lists.
    Returns:
        Inverse matrix as a numpy array.
    """
    det = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    if det == 0:
        raise ValueError("Matrix is not invertible (determinant is 0).")
    
    adj = compute_adjugate(matrix)
    inverse = (1 / det) * adj
    return inverse

# Example
C = [[1, 2], [3, 4]]

# Compute adjugate
adj = compute_adjugate(C)
print("Adjugate of C:")
print(adj)

# Compute inverse
inv = compute_inverse(C)
print("Inverse of C:")
print(np.round(inv, 4))

C = np.array(C, dtype=float)


Adjugate of C:
[[ 4 -2]
 [-3  1]]
Inverse of C:
[[-2.   1. ]
 [ 1.5 -0.5]]


### Numpy - Compute the Inverse of Matrix

In [9]:
C_inv = np.linalg.inv(C)
print("Inverse of C:")
print(np.round(inv, 4))

Inverse of C:
[[-2.   1. ]
 [ 1.5 -0.5]]
